# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Sakura"
license = "GPL-v3.0"
licenselink = "https://github.com/bohrium272/hugo-sakura/blob/master/LICENSE"
description = "Hugo Theme based on sakura.css"
homepage = "https://github.com/bohrium272/hugo-sakura"
tags = ["blog", "simple"]
features = ["blog", "simple"]
min_version = "0.41.0"

[author]
  name = "bohrium272"

[original]
  author = "Lukas Joswiak"
  homepage = "https://github.com/LukasJoswiak/etch"
  repo = "https://github.com/LukasJoswiak/etch"
