baseURL = "https://example.com"
title = "Sakura Demo"
theme = "sakura"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  sakuraTheme = ""
  mainSections = ["posts"]

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  unsafe= true
